spring.application.name=Payment-Gateway
server.port=8084

razorpay.key_id=rzp_test_RoHpC7vB30UOU6
razorpay.key_secret=jboYVPeAWvMkYQifhJjbDkls

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Use Railway's PUBLIC connection (not internal)
spring.datasource.url=jdbc:mysql://yamabiko.proxy.rlwy.net:40615/railway
spring.datasource.username=root
spring.datasource.password=mTfmjRjxHQAyoNMjjEZlOPLpEzEDrTaJ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dashdiggesh18@gmail.com
spring.mail.password=mhnj xfqx yydy kesf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




spring.mail.properties.mail.smtp.starttls.enable=true
